providers = ["python", "node"]

[variables]
  NIXPACKS_PYTHON_VERSION = "3.11"
  NIXPACKS_NODE_VERSION = "20"


[phases.build]
  cmds = [
    "cd webapp && npm install && npm run build && cd ..",
    "pip install -r requirements.txt"
  ]

[start]
  cmd = "python -m src.bot"
