providers = ["python", "node"]

[phases.setup]
  nixPkgs = ["python311", "nodejs_20"]

[phases.build]
  cmds = [
    "cd webapp && npm install && npm run build && cd ..",
    "pip install -r requirements.txt"
  ]

[start]
  cmd = "python -m src.bot"
